import json, os

def load_db():
    with open('data/private_colleges_ownership.json', 'r') as f:
        own = json.load(f)
    with open('data/private_college_sources.json', 'r') as f:
        src = json.load(f)
    return own, src

def save_db(own, src):
    own_dict = {str(x['SlNo']): x for x in own}
    src_dict = {str(x['SlNo']): x for x in src}
    
    sorted_own = sorted(own_dict.values(), key=lambda x: int(x['SlNo']))
    sorted_src = sorted(src_dict.values(), key=lambda x: int(x['SlNo']))
    
    with open('data/private_colleges_ownership.json', 'w') as f:
        json.dump(sorted_own, f, indent=2)
    with open('data/private_college_sources.json', 'w') as f:
        json.dump(sorted_src, f, indent=2)
    print(f"Total updated: {len(sorted_own)} records")

own, src = load_db()

north_west_records = [
  # --- UTTAR PRADESH ---
  {
    "SlNo": "659",
    "CollegeName": "Autonomous State Medical College and Hospital Gonda",
    "State": "Uttar Pradesh",
    "District": "Gonda",
    "University": "Atal Bihari Vajpayee Medical University Lucknow",
    "Management": "Society",
    "ParentOrganization": "Autonomous State Medical College Society Gonda (Govt of Uttar Pradesh)",
    "KeyPeople": [{"Name": "Department of Medical Education", "Role": "Governing Body", "Details": "Government of Uttar Pradesh"}],
    "PoliticalAffiliation": "State Government Autonomous Society.",
    "FundingSource": "Government of Uttar Pradesh budgetary allocations & PMSSY central scheme funds.",
    "SummaryReport": "State-administered autonomous medical college society established under the UP Department of Medical Education."
  },
  {
    "SlNo": "660",
    "CollegeName": "Autonomous State Medical College and Hospital Lakhimpur Kheri",
    "State": "Uttar Pradesh",
    "District": "Lakhimpur Kheri",
    "University": "Atal Bihari Vajpayee Medical University Lucknow",
    "Management": "Society",
    "ParentOrganization": "Autonomous State Medical College Society Lakhimpur Kheri (Govt of Uttar Pradesh)",
    "KeyPeople": [{"Name": "Department of Medical Education", "Role": "Governing Body", "Details": "Government of Uttar Pradesh"}],
    "PoliticalAffiliation": "State Government Autonomous Society.",
    "FundingSource": "Government of Uttar Pradesh budget & central health scheme allocations.",
    "SummaryReport": "State autonomous government medical college society in Lakhimpur Kheri."
  },
  {
    "SlNo": "664",
    "CollegeName": "Dr. B.S. Kushwah Medical College Kanpur",
    "State": "Uttar Pradesh",
    "District": "Kanpur Nagar",
    "University": "Atal Bihari Vajpayee Medical University Lucknow",
    "Management": "Private",
    "ParentOrganization": "Rama Educational Society",
    "KeyPeople": [
      {"Name": "Dr. Suraj B. S. Kushwah", "Role": "Chancellor", "Details": "Rama University"},
      {"Name": "Late Dr. B. S. Kushwah", "Role": "Founder", "Details": "Physician and educationist"}
    ],
    "PoliticalAffiliation": "None direct / Educational conglomerate in Kanpur & NCR.",
    "FundingSource": "Rama Group institutional fees, hospital operational income.",
    "SummaryReport": "Established in Kanpur under Rama Educational Society. Constituent of Rama University ecosystem. Self-financed."
  },
  {
    "SlNo": "665",
    "CollegeName": "SKS Hospital Medical College & Research Centre Mathura",
    "State": "Uttar Pradesh",
    "District": "Mathura",
    "University": "Atal Bihari Vajpayee Medical University Lucknow",
    "Management": "Private",
    "ParentOrganization": "SKS Educational Trust",
    "KeyPeople": [{"Name": "S. K. Sharma", "Role": "Chairman", "Details": "SKS Group of Institutions"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in Mathura under SKS Educational Trust. Self-financed."
  },
  {
    "SlNo": "667",
    "CollegeName": "Major S D Singh Medical College and Hospital Fathehgarh Farrukhabad",
    "State": "Uttar Pradesh",
    "District": "Farrukhabad",
    "University": "C.S.J.M. University Kanpur",
    "Management": "Trust",
    "ParentOrganization": "Major S. D. Singh University Trust",
    "KeyPeople": [{"Name": "Dr. Anar Singh Yadav", "Role": "Founder Chairman", "Details": "Former Member of Legislative Assembly (Samajwadi Party, Farrukhabad)"}],
    "PoliticalAffiliation": "Samajwadi Party Leader. Founded by former SP MLA Dr. Anar Singh Yadav.",
    "FundingSource": "Promoter capital, student tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2011 in Fatehgarh, Farrukhabad by SP politician Dr. Anar Singh Yadav. Self-financed."
  },
  {
    "SlNo": "671",
    "CollegeName": "Teerthanker Mahaveer Medical College Moradabad",
    "State": "Uttar Pradesh",
    "District": "Moradabad",
    "University": "Teerthanker Mahaveer University Moradabad",
    "Management": "Trust",
    "ParentOrganization": "Teerthanker Mahaveer Institute / TMU Deemed University Trust",
    "KeyPeople": [{"Name": "Suresh Jain", "Role": "Chancellor & Founder", "Details": "Industrialist, Jain community leader, and former BJP political figure"}],
    "PoliticalAffiliation": "Jain Minority Trust / BJP Connections. Founded by Jain leader and former BJP figure Suresh Jain.",
    "FundingSource": "TMU Deemed University fees, 1000-bed super-specialty hospital clinical income.",
    "SummaryReport": "Established in 2008 in Moradabad as flagship Jain minority medical college of TMU Private University. Self-financed."
  },
  {
    "SlNo": "673",
    "CollegeName": "Muzaffarnagar Medical College Muzaffarnagar",
    "State": "Uttar Pradesh",
    "District": "Muzaffarnagar",
    "University": "Ch. Charan Singh University Meerut",
    "Management": "Trust",
    "ParentOrganization": "Triveni Educational Social Welfare Society",
    "KeyPeople": [{"Name": "Satpal Singh", "Role": "Chairman", "Details": "Triveni Educational Society"}],
    "PoliticalAffiliation": "Local political connections in Western Uttar Pradesh.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2006 in Muzaffarnagar by Triveni Educational Social Welfare Society. Self-financed."
  },
  {
    "SlNo": "674",
    "CollegeName": "Santosh Medical College Ghaziabad",
    "State": "Uttar Pradesh",
    "District": "Ghaziabad",
    "University": "Santosh University",
    "Management": "Trust",
    "ParentOrganization": "Maharaji Educational Trust",
    "KeyPeople": [
      {"Name": "Dr. P. Mahalingam", "Role": "Founder & Chancellor", "Details": "Cardiologist and founder of Santosh Trust"},
      {"Name": "Dr. Santosh Mahalingam", "Role": "Trustee", "Details": "Santosh University"}
    ],
    "PoliticalAffiliation": "None direct / Premier private deemed medical university in NCR.",
    "FundingSource": "Deemed university tuition fees, 800-bed hospital clinical income.",
    "SummaryReport": "Established in 1996 in Ghaziabad by Dr. P. Mahalingam under Maharaji Educational Trust. Self-financed deemed university."
  },
  {
    "SlNo": "679",
    "CollegeName": "Era Lucknow Medical College Lucknow",
    "State": "Uttar Pradesh",
    "District": "Lucknow",
    "University": "Era University Lucknow",
    "Management": "Trust",
    "ParentOrganization": "Era Educational Trust (EET)",
    "KeyPeople": [
      {"Name": "Mohsin Ali Khan", "Role": "Chancellor", "Details": "Era University"},
      {"Name": "Prof. T. D. Ahmad", "Role": "Founder", "Details": "Eminent medical educator"}
    ],
    "PoliticalAffiliation": "None direct / Muslim Minority Private University.",
    "FundingSource": "Era University fees, Era Hospital clinical revenues.",
    "SummaryReport": "Established in 2001 in Sarfarazganj, Lucknow as a premier Muslim minority medical college under Era Educational Trust. Self-financed."
  },
  {
    "SlNo": "682",
    "CollegeName": "Rohilkhand Medical College & Hospital Bareilly",
    "State": "Uttar Pradesh",
    "District": "Bareilly",
    "University": "Bareilly International University Bareilly",
    "Management": "Trust",
    "ParentOrganization": "Rohilkhand Educational Charitable Trust",
    "KeyPeople": [{"Name": "Dr. Keshav Kumar Agrawal", "Role": "Founder & Chancellor", "Details": "Surgeon and Chancellor of Bareilly International University"}],
    "PoliticalAffiliation": "None direct / Educational conglomerate in Rohilkhand region.",
    "FundingSource": "University tuition fees, hospital operational income.",
    "SummaryReport": "Established in 2006 in Bareilly by Dr. Keshav Kumar Agrawal under Rohilkhand Educational Charitable Trust. Self-financed."
  },
  {
    "SlNo": "683",
    "CollegeName": "Subharti Medical College Meerut",
    "State": "Uttar Pradesh",
    "District": "Meerut",
    "University": "Swami Vivekanand Subharti University Meerut",
    "Management": "Trust",
    "ParentOrganization": "Swami Vivekanand Subharti Joint Trust / MTV Trust",
    "KeyPeople": [
      {"Name": "Dr. Atul Krishna", "Role": "Founder", "Details": "Surgeon, freedom fighter family member, and founder of Subharti University"},
      {"Name": "Stuti Narain Kacker", "Role": "Chancellor", "Details": "Former IAS officer"}
    ],
    "PoliticalAffiliation": "None direct / Major private trust university in Meerut.",
    "FundingSource": "Subharti University fees, Chhatrapati Shivaji Subharti Hospital earnings.",
    "SummaryReport": "Established in 1999 in Meerut by Dr. Atul Krishna under Subharti Trust. Self-financed."
  },
  {
    "SlNo": "685",
    "CollegeName": "Hind Institute of Medical Sciences Barabanki",
    "State": "Uttar Pradesh",
    "District": "Barabanki",
    "University": "Dr. Ram Manohar Lohia Avadh University Faizabad",
    "Management": "Trust",
    "ParentOrganization": "Hind Charitable Trust",
    "KeyPeople": [{"Name": "Richa Mishra", "Role": "Chairperson", "Details": "Hind Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2009 at Safedabad, Barabanki by Hind Charitable Trust. Self-financed."
  },
  {
    "SlNo": "696",
    "CollegeName": "Naraina Medical College & Research Centre Kanpur",
    "State": "Uttar Pradesh",
    "District": "Kanpur Nagar",
    "University": "Atal Bihari Vajpayee Medical University Lucknow",
    "Management": "Society",
    "ParentOrganization": "Naraina Vidya Peeth Educational Trust",
    "KeyPeople": [{"Name": "R. P. Trivedi", "Role": "Chairman", "Details": "Naraina Group"}],
    "PoliticalAffiliation": "None direct / Private educational trust.",
    "FundingSource": "Group reserves, tuition fees, hospital income.",
    "SummaryReport": "Established in Kanpur by Naraina Vidya Peeth Educational Trust. Self-financed."
  },
  {
    "SlNo": "697",
    "CollegeName": "Noida International Institute Of Medical Sciences Noida",
    "State": "Uttar Pradesh",
    "District": "Gautam Buddha Nagar",
    "University": "Noida International University",
    "Management": "Trust",
    "ParentOrganization": "Transchal Charitable Trust / Noida International University",
    "KeyPeople": [
      {"Name": "Dr. Vikram Singh", "Role": "Chancellor", "Details": "Former Director General of Police (DGP, Uttar Pradesh)"},
      {"Name": "Dr. Devesh Kumar Singh", "Role": "Chairman", "Details": "NIU Group"}
    ],
    "PoliticalAffiliation": "Prominent Administrative Stature. Chancellor Dr. Vikram Singh is a former DGP of Uttar Pradesh.",
    "FundingSource": "Noida International University tuition fees, hospital clinical income.",
    "SummaryReport": "Constituent medical college of Noida International University at Greater Noida, chaired by former UP DGP Dr. Vikram Singh. Self-financed."
  },
  {
    "SlNo": "698",
    "CollegeName": "United Institute of Medical Sciences Allahabad",
    "State": "Uttar Pradesh",
    "District": "Prayagraj",
    "University": "Prof. Rajendra Singh Rajju Bhaiya University Prayagraj",
    "Management": "Society",
    "ParentOrganization": "United Group of Institutions (Shiv Ram Das Gulati Memorial Society)",
    "KeyPeople": [
      {"Name": "Jagdish Gulati", "Role": "President", "Details": "United Group"},
      {"Name": "Gulab Chandra Jaiswal", "Role": "Founder Visionary", "Details": "Industrialist"}
    ],
    "PoliticalAffiliation": "None direct / Educational conglomerate in Eastern UP.",
    "FundingSource": "United Group institutional funds, student fees, hospital revenue.",
    "SummaryReport": "Established in 2020 at Rawatpur, Prayagraj by United Group of Institutions. Self-financed."
  },
  {
    "SlNo": "706",
    "CollegeName": "National Capital Region Institute of Medical Sciences Meerut",
    "State": "Uttar Pradesh",
    "District": "Meerut",
    "University": "Ch. Charan Singh University Meerut",
    "Management": "Society",
    "ParentOrganization": "Kalka Educational Society",
    "KeyPeople": [{"Name": "J. P. Sharma", "Role": "Chairman", "Details": "Kalka Group"}],
    "PoliticalAffiliation": "None direct / Educational society.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2018 in Meerut by Kalka Educational Society. Self-financed."
  },
  {
    "SlNo": "707",
    "CollegeName": "G.S. Medical College & Hospital Hapur",
    "State": "Uttar Pradesh",
    "District": "Hapur",
    "University": "Ch. Charan Singh University Meerut",
    "Management": "Trust",
    "ParentOrganization": "Jaiprakash Educational Trust",
    "KeyPeople": [{"Name": "G. S. Sharma", "Role": "Chairman", "Details": "G.S. Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital revenue.",
    "SummaryReport": "Established in 2016 at Pilkhuwa, Hapur by Jaiprakash Educational Trust. Self-financed."
  },
  {
    "SlNo": "709",
    "CollegeName": "Varun Arjun Medical College Banthra Shahjahanpur",
    "State": "Uttar Pradesh",
    "District": "Shahjahanpur",
    "University": "Mahatma Jyotiba Phule Rohilkhand University",
    "Management": "Trust",
    "ParentOrganization": "Rohilkhand Educational Charitable Trust",
    "KeyPeople": [{"Name": "Dr. Keshav Kumar Agrawal", "Role": "Chairman", "Details": "Rohilkhand Group"}],
    "PoliticalAffiliation": "None direct / Rohilkhand educational trust.",
    "FundingSource": "Tuition fees, hospital operational income.",
    "SummaryReport": "Established in 2016 at Banthra, Shahjahanpur by Rohilkhand Educational Trust. Self-financed."
  },
  {
    "SlNo": "710",
    "CollegeName": "Saraswati Medical College Unnao",
    "State": "Uttar Pradesh",
    "District": "Unnao",
    "University": "CSJM University Kanpur",
    "Management": "Trust",
    "ParentOrganization": "Saraswati Educational Trust",
    "KeyPeople": [{"Name": "Rama Shankar Sharma", "Role": "Chairman", "Details": "Saraswati Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2016 in Unnao by Saraswati Educational Trust. Self-financed."
  },
  {
    "SlNo": "711",
    "CollegeName": "Krishna Mohan Medical College & Hospital Mathura",
    "State": "Uttar Pradesh",
    "District": "Mathura",
    "University": "Dr B R Ambedkar University Agra",
    "Management": "Society",
    "ParentOrganization": "Krishna Mohan Educational Society",
    "KeyPeople": [{"Name": "Monu Yadav", "Role": "Chairman", "Details": "Krishna Mohan Group"}],
    "PoliticalAffiliation": "Local political influence in Mathura region.",
    "FundingSource": "Tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2016 in Mathura by Krishna Mohan Educational Society. Self-financed."
  },
  {
    "SlNo": "712",
    "CollegeName": "Venkateshwara Institute of Medical Sciences Gajraula",
    "State": "Uttar Pradesh",
    "District": "Amroha",
    "University": "Shri Venkateshwara University Gajraula",
    "Management": "Trust",
    "ParentOrganization": "Venkateshwara Group / Sri Venkateshwara University",
    "KeyPeople": [{"Name": "Dr. Sudhir Giri", "Role": "Founder & Chancellor", "Details": "Industrialist and educationist"}],
    "PoliticalAffiliation": "None direct / Major educational group in Rohilkhand/NCR.",
    "FundingSource": "University fees, hospital clinical earnings.",
    "SummaryReport": "Established in 2016 at Gajraula, Amroha by Dr. Sudhir Giri. Constituent of Shri Venkateshwara University. Self-financed."
  },
  {
    "SlNo": "713",
    "CollegeName": "Prasad Institute of Medical Sciences Lucknow",
    "State": "Uttar Pradesh",
    "District": "Lucknow",
    "University": "Dr. Ram Manohar Lohia Avadh University Faizabad",
    "Management": "Trust",
    "ParentOrganization": "Prasad Educational Trust",
    "KeyPeople": [{"Name": "B. P. Yadav", "Role": "Founder Chairman", "Details": "Political leader (Samajwadi Party connection) and educationist"}],
    "PoliticalAffiliation": "Samajwadi Party Connections. Founder B. P. Yadav has active SP political affiliations.",
    "FundingSource": "Trust funds, student tuition fees, hospital operational income.",
    "SummaryReport": "Established in 2016 at Banthra, Kanpur Road, Lucknow by B. P. Yadav under Prasad Educational Trust. Self-financed."
  },
  {
    "SlNo": "714",
    "CollegeName": "T S Misra Medical College & Hospital Amusi Lucknow",
    "State": "Uttar Pradesh",
    "District": "Lucknow",
    "University": "T.S. Misra University",
    "Management": "Private",
    "ParentOrganization": "Vedic and Educational Society",
    "KeyPeople": [{"Name": "T. S. Misra", "Role": "Chairman", "Details": "Vedic Educational Society"}],
    "PoliticalAffiliation": "None direct / Private educational trust.",
    "FundingSource": "Tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2016 at Amausi, Lucknow by Vedic and Educational Society. Self-financed."
  },
  {
    "SlNo": "716",
    "CollegeName": "K.D. Medical College Hospital & Research Centre Mathura",
    "State": "Uttar Pradesh",
    "District": "Mathura",
    "University": "Dr B R Ambedkar University Agra",
    "Management": "Society",
    "ParentOrganization": "Rajiv Memorial Academic City / RK Group",
    "KeyPeople": [{"Name": "R. K. Gupta", "Role": "Chairman", "Details": "RK Group of Institutions"}],
    "PoliticalAffiliation": "None direct / Educational group.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2015 at Akbarpur, Mathura by Rajiv Memorial Academic City. Self-financed."
  },
  {
    "SlNo": "718",
    "CollegeName": "Heritage Institute of Medical Sciences Varanasi",
    "State": "Uttar Pradesh",
    "District": "Varanasi",
    "University": "Mahatma Gandhi Kashi Vidyapith Varanasi",
    "Management": "Private",
    "ParentOrganization": "Heritage Hospitals Ltd / Heritage Society",
    "KeyPeople": [{"Name": "Dr. Siddharth Rai", "Role": "Chairman & MD", "Details": "Heritage Hospitals Varanasi"}],
    "PoliticalAffiliation": "None direct / Prominent healthcare group in Varanasi.",
    "FundingSource": "Heritage Hospitals Ltd corporate capital, tuition fees, super-specialty hospital income.",
    "SummaryReport": "Established in 2015 at Bhadwar, Varanasi by Heritage Hospitals Ltd. Self-financed."
  },
  {
    "SlNo": "719",
    "CollegeName": "Hind Institute of Medical Sciences Sitapur",
    "State": "Uttar Pradesh",
    "District": "Sitapur",
    "University": "King Georges Medical University Lucknow",
    "Management": "Trust",
    "ParentOrganization": "Hind Charitable Trust",
    "KeyPeople": [{"Name": "Richa Mishra", "Role": "Chairperson", "Details": "Hind Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Hind Trust funds, tuition fees, hospital clinical earnings.",
    "SummaryReport": "Established in 2015 at Ataria, Sitapur by Hind Charitable Trust. Self-financed."
  },
  {
    "SlNo": "720",
    "CollegeName": "F.H. Medical College & Hospital Etamdapur Agra",
    "State": "Uttar Pradesh",
    "District": "Agra",
    "University": "Dr B R Ambedkar University Agra",
    "Management": "Trust",
    "ParentOrganization": "F. H. Educational Trust",
    "KeyPeople": [{"Name": "Zahir Ahmad", "Role": "Managing Trustee", "Details": "F.H. Group"}],
    "PoliticalAffiliation": "None direct / Muslim Minority Medical College.",
    "FundingSource": "Minority trust funds, tuition fees, hospital revenue.",
    "SummaryReport": "Established in 2014 at Etmadpur, Agra as a Muslim minority medical college by F. H. Educational Trust. Self-financed."
  },
  {
    "SlNo": "721",
    "CollegeName": "Rajshree Medical Research Institute Bareilly",
    "State": "Uttar Pradesh",
    "District": "Bareilly",
    "University": "M J P Rohilkhand University",
    "Management": "Trust",
    "ParentOrganization": "Rajshree Educational Trust",
    "KeyPeople": [{"Name": "Rajendra Kumar Agrawal", "Role": "Chairman", "Details": "Rajshree Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2014 in Bareilly by Rajshree Educational Trust. Self-financed."
  },
  {
    "SlNo": "723",
    "CollegeName": "Integral Institute of Medical Sciences & Research Lucknow",
    "State": "Uttar Pradesh",
    "District": "Lucknow",
    "University": "Integral University Lucknow",
    "Management": "Private",
    "ParentOrganization": "Integral University / Islamic Educational Society",
    "KeyPeople": [{"Name": "Prof. Syed Waseem Akhtar", "Role": "Founder & Chancellor", "Details": "Eminent educationist and founder of Integral University"}],
    "PoliticalAffiliation": "None direct / Premier Muslim Minority Deemed/State Private University.",
    "FundingSource": "Integral University tuition fees, hospital clinical earnings.",
    "SummaryReport": "Established in 2013 at Dasauli, Lucknow as constituent college of Integral University. Self-funded Muslim minority university."
  },
  {
    "SlNo": "725",
    "CollegeName": "Mayo Institute of Medical Sciences Barabanki",
    "State": "Uttar Pradesh",
    "District": "Barabanki",
    "University": "Dr. Ram Manohar Lohia Avadh University Faizabad",
    "Management": "Trust",
    "ParentOrganization": "Bodhisattva Charitable Trust",
    "KeyPeople": [{"Name": "Dr. K. N. Singh", "Role": "Chairman", "Details": "Mayo Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital operational income.",
    "SummaryReport": "Established in 2012 in Barabanki by Bodhisattva Charitable Trust. Self-financed."
  },
  {
    "SlNo": "727",
    "CollegeName": "Rama Medical College Hospital and Research Centre Hapur",
    "State": "Uttar Pradesh",
    "District": "Hapur",
    "University": "Dr B R Ambedkar University Agra",
    "Management": "Trust",
    "ParentOrganization": "Rama Educational Society",
    "KeyPeople": [{"Name": "Dr. Suraj B. S. Kushwah", "Role": "Chancellor", "Details": "Rama Group"}],
    "PoliticalAffiliation": "None direct / Rama Group.",
    "FundingSource": "Rama Group funds, tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2011 in Hapur by Rama Educational Society. Self-financed."
  },
  {
    "SlNo": "728",
    "CollegeName": "Career Instt. Of Medical Sciences & Hospital Lucknow",
    "State": "Uttar Pradesh",
    "District": "Lucknow",
    "University": "Dr. Ram Manohar Lohia Avadh University Faizabad",
    "Management": "Trust",
    "ParentOrganization": "Career Educational Trust",
    "KeyPeople": [{"Name": "Azmat Ali Khan", "Role": "Chairman", "Details": "Career Group of Institutions"}],
    "PoliticalAffiliation": "None direct / Muslim Minority Medical Trust.",
    "FundingSource": "Minority trust reserves, tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2011 at IIM Road, Lucknow as a Muslim minority medical college operated by Career Educational Trust. Self-financed."
  },
  {
    "SlNo": "729",
    "CollegeName": "School of Medical Sciences & Research Greater Noida",
    "State": "Uttar Pradesh",
    "District": "Gautam Buddha Nagar",
    "University": "Sharda University",
    "Management": "Trust",
    "ParentOrganization": "Sharda Educational Trust / Sharda University",
    "KeyPeople": [
      {"Name": "Pradeep Kumar Gupta", "Role": "Founder & Chancellor", "Details": "Founder of Sharda Group of Institutions"},
      {"Name": "Y. K. Gupta", "Role": "Pro-Chancellor", "Details": "Sharda University"}
    ],
    "PoliticalAffiliation": "None direct / Major private university group.",
    "FundingSource": "Sharda University tuition fees, 900-bed Sharda Hospital clinical income.",
    "SummaryReport": "Established in 2009 at Greater Noida as constituent medical college of Sharda University. Self-financed."
  },
  {
    "SlNo": "730",
    "CollegeName": "Rama Medical College and Hospital Kanpur",
    "State": "Uttar Pradesh",
    "District": "Kanpur Nagar",
    "University": "Dr B R Ambedkar University Agra",
    "Management": "Trust",
    "ParentOrganization": "Rama Educational Society",
    "KeyPeople": [{"Name": "Dr. Suraj B. S. Kushwah", "Role": "Chancellor", "Details": "Rama Group"}],
    "PoliticalAffiliation": "None direct / Rama Educational Society.",
    "FundingSource": "Rama Group reserves, tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2008 in Mandhana, Kanpur by Rama Educational Society. Self-financed."
  },
  {
    "SlNo": "731",
    "CollegeName": "Saraswati Institute of Medical Sciences Hapur",
    "State": "Uttar Pradesh",
    "District": "Hapur",
    "University": "Ch. Charan Singh University Meerut",
    "Management": "Trust",
    "ParentOrganization": "Saraswati Educational Trust",
    "KeyPeople": [{"Name": "J. Ramachandran", "Role": "Chairman", "Details": "Saraswati Educational Institutions"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2008 at Anwarpur, Hapur by Saraswati Educational Trust. Self-financed."
  },
  {
    "SlNo": "732",
    "CollegeName": "Shri Ram Murti Smarak Institute of Medical Sciences Bareilly",
    "State": "Uttar Pradesh",
    "District": "Bareilly",
    "University": "M J P Rohilkhand University",
    "Management": "Trust",
    "ParentOrganization": "Shri Ram Murti Smarak Trust (SRMS Trust)",
    "KeyPeople": [{"Name": "Dev Murti", "Role": "Founder Chairman", "Details": "Eminent industrialist, educationist, and philanthropist"}],
    "PoliticalAffiliation": "None direct / Premier non-profit educational trust in Rohilkhand.",
    "FundingSource": "SRMS Trust endowments, student tuition fees, 950-bed super-specialty hospital earnings.",
    "SummaryReport": "Established in 2002 in Bareilly by Dev Murti under SRMS Trust. Premier self-financed medical college and super-specialty hospital."
  },

  # --- GUJARAT ---
  {
    "SlNo": "106",
    "CollegeName": "Bhagyoday Medical College",
    "State": "Gujarat",
    "District": "Mehsana",
    "University": "Gujarat University",
    "Management": "Trust",
    "ParentOrganization": "Bhagyoday General Hospital Trust Kadi",
    "KeyPeople": [{"Name": "Trustees", "Role": "Governing Board", "Details": "Kadi Charitable Trust"}],
    "PoliticalAffiliation": "None direct / Community trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established at Kadi, Mehsana district under Bhagyoday Charitable Trust. Self-financed."
  },
  {
    "SlNo": "107",
    "CollegeName": "SAL Institute of Medical Sciences Ahmedabad",
    "State": "Gujarat",
    "District": "Ahmedabad",
    "University": "Gujarat University",
    "Management": "Trust",
    "ParentOrganization": "Shah Education Trust / SAL Hospital Group",
    "KeyPeople": [{"Name": "Dr. Rajendra Shah", "Role": "Chairman & Founder", "Details": "Renowned cardiologist and chairman of SAL Hospital"}],
    "PoliticalAffiliation": "None direct / Leading healthcare enterprise group in Ahmedabad.",
    "FundingSource": "SAL Hospital Group capital, tuition fees, clinical hospital income.",
    "SummaryReport": "Established at Bhadaj, Ahmedabad by Dr. Rajendra Shah under Shah Education Trust. Self-financed."
  },
  {
    "SlNo": "108",
    "CollegeName": "Swaminarayan Institute of Medical Sciences & Research",
    "State": "Gujarat",
    "District": "Gandhinagar",
    "University": "Swaminarayan University",
    "Management": "Trust",
    "ParentOrganization": "Shree Swaminarayan Vishwamangal Gurukul Trust",
    "KeyPeople": [{"Name": "Swami Keshavcharandasji", "Role": "Managing Trustee", "Details": "Swaminarayan Sansthan"}],
    "PoliticalAffiliation": "Spiritual Trust with wide political reverence in Gujarat.",
    "FundingSource": "Gurukul trust donations, university tuition fees, hospital revenues.",
    "SummaryReport": "Constituent medical college of Swaminarayan University at Saij, Kalol, Gandhinagar, operated by Swaminarayan Gurukul Trust. Self-funded."
  },
  {
    "SlNo": "114",
    "CollegeName": "SBKS Medical Instt. & Research Centre Vadodra",
    "State": "Gujarat",
    "District": "Vadodara",
    "University": "Sumandeep Vidyapeeth University Vadodara",
    "Management": "Trust",
    "ParentOrganization": "Sumandeep Vidyapeeth Deemed University Trust",
    "KeyPeople": [{"Name": "Mansukh Shah", "Role": "Founder", "Details": "Educationist"}],
    "PoliticalAffiliation": "Jain Minority Trust.",
    "FundingSource": "Deemed university tuition fees, Dhiraj General Hospital clinical income.",
    "SummaryReport": "Established in 2002 at Piparia, Vadodara. Flagship constituent of Sumandeep Vidyapeeth Deemed University. Self-financed."
  },
  {
    "SlNo": "115",
    "CollegeName": "CU Shah Medical College Surendra Nagar",
    "State": "Gujarat",
    "District": "Surendranagar",
    "University": "Saurashtra University",
    "Management": "Trust",
    "ParentOrganization": "Vardhman Charitable Trust",
    "KeyPeople": [{"Name": "Late C. U. Shah", "Role": "Founder", "Details": "Industrialist and philanthropist"}],
    "PoliticalAffiliation": "None direct / Philanthropic Jain trust.",
    "FundingSource": "Vardhman Trust endowments, student tuition fees, hospital clinical earnings.",
    "SummaryReport": "Established in 2000 in Dudhrej, Surendranagar by industrialist C. U. Shah. Self-funded trust medical college."
  },
  {
    "SlNo": "120",
    "CollegeName": "Dr. Kiran C. Patel Medical College and Research Institute Bharuch",
    "State": "Gujarat",
    "District": "Bharuch",
    "University": "Veer Narmad South Gujarat University",
    "Management": "Trust",
    "ParentOrganization": "Dr. Kiran C. Patel Educational Trust",
    "KeyPeople": [{"Name": "Dr. Kiran C. Patel", "Role": "Founder & Benefactor", "Details": "Indian-American billionaire cardiologist, entrepreneur, and philanthropist"}],
    "PoliticalAffiliation": "Global Philanthropist (High-level diplomatic & national stature).",
    "FundingSource": "Dr. Kiran C. Patel philanthropic endowment (USD multi-million contribution), tuition fees, hospital revenue.",
    "SummaryReport": "Established in 2020 in Bharuch through monumental endowment by Indian-American billionaire cardiologist Dr. Kiran C. Patel. Self-funded philanthropic trust."
  },
  {
    "SlNo": "121",
    "CollegeName": "Shantabaa Medical College Amreli",
    "State": "Gujarat",
    "District": "Amreli",
    "University": "Saurashtra University",
    "Management": "Trust",
    "ParentOrganization": "Gajera Trust",
    "KeyPeople": [{"Name": "Vasant Gajera", "Role": "Founder Chairman", "Details": "Diamond industrialist (Laxmi Diamond) and philanthropist"}],
    "PoliticalAffiliation": "None direct / Leading diamond industry philanthropic trust.",
    "FundingSource": "Gajera Trust diamond business capital, tuition fees, Civil Hospital PPP operational income.",
    "SummaryReport": "Established in 2019 in Amreli by diamond tycoon Vasant Gajera under Gajera Trust in PPP with Gujarat Govt. Self-financed."
  },
  {
    "SlNo": "122",
    "CollegeName": "Nootan Medical College and Research Centre Mehsana",
    "State": "Gujarat",
    "District": "Mehsana",
    "University": "Sankalchand Patel University",
    "Management": "Trust",
    "ParentOrganization": "Nootan Sarva Vidyalaya Kelavani Mandal / Sankalchand Patel University",
    "KeyPeople": [{"Name": "Prakash Patel", "Role": "President", "Details": "Sankalchand Patel University"}],
    "PoliticalAffiliation": "Local political connections in North Gujarat.",
    "FundingSource": "University tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2019 in Visnagar, Mehsana. Constituent of Sankalchand Patel University. Self-financed."
  },
  {
    "SlNo": "123",
    "CollegeName": "Dr. N.D. Desai Faculty of Medical Science and Research Nadiad",
    "State": "Gujarat",
    "District": "Kheda",
    "University": "Dharmsinh Desai University",
    "Management": "Private",
    "ParentOrganization": "Dharmsinh Desai University Trust",
    "KeyPeople": [
      {"Name": "Dr. H. M. Desai", "Role": "Vice Chancellor", "Details": "Dharmsinh Desai University"},
      {"Name": "Late Dharmsinh Dadubhai Desai", "Role": "Founder", "Details": "Former Member of Parliament and industrialist"}
    ],
    "PoliticalAffiliation": "Historical MP Family. Founded by family of late MP Dharmsinh Desai.",
    "FundingSource": "DDU University tuition fees, hospital operational income.",
    "SummaryReport": "Constituent medical faculty of Dharmsinh Desai University in Nadiad, established under DDU Trust. Self-financed."
  },
  {
    "SlNo": "124",
    "CollegeName": "Kiran Medical College Surat",
    "State": "Gujarat",
    "District": "Surat",
    "University": "Veer Narmad South Gujarat University",
    "Management": "Trust",
    "ParentOrganization": "Samast Patidar Samaj / Kiran Hospital Trust",
    "KeyPeople": [{"Name": "Mathur Savani", "Role": "Chairman", "Details": "Surat diamond industrialist and Patidar community leader"}],
    "PoliticalAffiliation": "Patidar Community Apex Body; strong civic and political presence in Surat.",
    "FundingSource": "Surat diamond industry philanthropic donations, tuition fees, Kiran Super-specialty Hospital earnings.",
    "SummaryReport": "Established in Surat under Samast Patidar Samaj trust led by diamond industrialist Mathur Savani. Self-funded philanthropic trust."
  },
  {
    "SlNo": "125",
    "CollegeName": "Zydus Medical College & Hospital Dahod",
    "State": "Gujarat",
    "District": "Dahod",
    "University": "Shri Govind Guru University Godhra",
    "Management": "Trust",
    "ParentOrganization": "Zydus UNICEF Healthcare Trust / Zydus Lifesciences Group",
    "KeyPeople": [{"Name": "Pankaj R. Patel", "Role": "Chairman", "Details": "Padma Bhushan awardee, Chairman of Zydus Lifesciences Ltd"}],
    "PoliticalAffiliation": "None direct / Top Indian pharma corporate house in PPP with Gujarat Govt.",
    "FundingSource": "Zydus Lifesciences CSR & corporate capital, Gujarat Govt PPP subsidy, student tuition fees.",
    "SummaryReport": "Established in 2018 at Dahod under PPP policy between Gujarat Govt and Zydus Lifesciences (Pankaj Patel). Self-funded corporate PPP trust."
  },
  {
    "SlNo": "126",
    "CollegeName": "Banas Medical College and Research Institute Palanpur",
    "State": "Gujarat",
    "District": "Banaskantha",
    "University": "Hemchandracharya North Gujarat University Patan",
    "Management": "Trust",
    "ParentOrganization": "Galbabhai Nanjibhai Patel Education Trust / Banas Dairy Cooperative",
    "KeyPeople": [{"Name": "Shankar Chaudhary", "Role": "Chairman", "Details": "Speaker of Gujarat Legislative Assembly (BJP) and Chairman of Banas Dairy"}],
    "PoliticalAffiliation": "BJP Speaker of Assembly. Chaired by Shankar Chaudhary, Speaker of the Gujarat Legislative Assembly.",
    "FundingSource": "Banas Dairy cooperative surplus reserves, student tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2018 in Palanpur by Banas Dairy cooperative trust, headed by Assembly Speaker Shankar Chaudhary. Self-funded cooperative trust."
  },
  {
    "SlNo": "128",
    "CollegeName": "Dr. M.K. Shah Medical College & Research Centre Ahmedabad",
    "State": "Gujarat",
    "District": "Ahmedabad",
    "University": "Gujarat University",
    "Management": "Trust",
    "ParentOrganization": "Saraswati Educational Trust",
    "KeyPeople": [{"Name": "Dr. M. K. Shah", "Role": "Founder Chairman", "Details": "SMS Hospital Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2017 at Chandkheda, Ahmedabad by Saraswati Educational Trust. Self-financed."
  },
  {
    "SlNo": "129",
    "CollegeName": "Parul Institute of Medical Sciences & Research Vadodara",
    "State": "Gujarat",
    "District": "Vadodara",
    "University": "Parul University",
    "Management": "Private",
    "ParentOrganization": "Parul University Trust / Parul Arogya Seva Mandal",
    "KeyPeople": [{"Name": "Dr. Devanshu Patel", "Role": "President", "Details": "Parul University"}],
    "PoliticalAffiliation": "None direct / Leading private university in Gujarat.",
    "FundingSource": "Parul University tuition fees, 750-bed Parul Sevashram Hospital revenues.",
    "SummaryReport": "Established in 2016 at Limda, Vadodara as constituent college of Parul Private University. Self-financed."
  },
  {
    "SlNo": "135",
    "CollegeName": "GCS Medical College Ahmedabad",
    "State": "Gujarat",
    "District": "Ahmedabad",
    "University": "Gujarat University",
    "Management": "Trust",
    "ParentOrganization": "Gujarat Cancer Society (GCS Trust)",
    "KeyPeople": [
      {"Name": "Chief Minister of Gujarat", "Role": "Ex-Officio President", "Details": "Government of Gujarat"},
      {"Name": "Pankaj R. Patel", "Role": "Executive Chairman", "Details": "Zydus Lifesciences"}
    ],
    "PoliticalAffiliation": "Apex State Charitable Trust (Chaired ex-officio by the Chief Minister of Gujarat).",
    "FundingSource": "GCS Trust endowments, philanthropic donations, student tuition fees, hospital operational income.",
    "SummaryReport": "Established in 2011 in Naroda, Ahmedabad by historic Gujarat Cancer Society (est. 1961), chaired ex-officio by the Chief Minister of Gujarat. Self-funded philanthropic trust."
  },
  {
    "SlNo": "138",
    "CollegeName": "Gujarat Adani Institute of Medical Sciences Bhuj",
    "State": "Gujarat",
    "District": "Kutch",
    "University": "KSKV Kachchh University Bhuj",
    "Management": "Trust",
    "ParentOrganization": "Adani Education & Research Foundation (Adani Group) / Govt of Gujarat PPP",
    "KeyPeople": [
      {"Name": "Gautam Adani", "Role": "Founder & Chairman", "Details": "Chairman of Adani Group"},
      {"Name": "Priti Adani", "Role": "Chairperson", "Details": "Adani Foundation"}
    ],
    "PoliticalAffiliation": "High-Stature Corporate House (Adani Group) in formal PPP partnership with Govt of Gujarat.",
    "FundingSource": "Adani Group corporate funding & CSR capital, GK General Hospital PPP clinical earnings, student tuition fees.",
    "SummaryReport": "Established in 2009 in Bhuj, Kutch as India's first high-profile PPP medical college between Adani Education Foundation (Gautam Adani) and Govt of Gujarat. Self-financed PPP trust."
  },
  {
    "SlNo": "142",
    "CollegeName": "Ananya College of Medicine & Research Kalol",
    "State": "Gujarat",
    "District": "Gandhinagar",
    "University": "Gujarat University Ahmedabad",
    "Management": "Private",
    "ParentOrganization": "Ananya Educational Trust",
    "KeyPeople": [{"Name": "Trustees", "Role": "Management", "Details": "Ananya Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Medical college at Kalol, Gandhinagar operated by Ananya Educational Trust. Self-financed."
  },
  {
    "SlNo": "146",
    "CollegeName": "Pramukhswami Medical College Karmsad",
    "State": "Gujarat",
    "District": "Anand",
    "University": "Bhaikaka University",
    "Management": "Trust",
    "ParentOrganization": "Charutar Arogya Mandal (CAM Trust)",
    "KeyPeople": [
      {"Name": "Dr. Amrita Patel", "Role": "Chairman", "Details": "Padma Bhushan awardee, former Chairman of National Dairy Development Board (NDDB)"},
      {"Name": "Late H. M. Patel", "Role": "Founder", "Details": "Former Union Finance Minister and Home Minister of India"}
    ],
    "PoliticalAffiliation": "Historical National Stature. Founded by former Union Finance Minister H. M. Patel; chaired by NDDB pioneer Dr. Amrita Patel.",
    "FundingSource": "Charutar Arogya Mandal trust endowments, student tuition fees, Shree Krishna Hospital clinical earnings.",
    "SummaryReport": "Established in 1987 in Karamsad, Anand by Union Minister H. M. Patel under Charutar Arogya Mandal. Flagship constituent of Bhaikaka University. Self-funded philanthropic trust."
  },

  # --- MADHYA PRADESH ---
  {
    "SlNo": "299",
    "CollegeName": "School of Medical Sciences Sri Satya Sai University of Technology and Medical Sciences Sehore",
    "State": "Madhya Pradesh",
    "District": "Sehore",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Society",
    "ParentOrganization": "Sri Satya Sai Group of Institutions Sehore",
    "KeyPeople": [{"Name": "Dr. Sunil Kapoor", "Role": "Chairman", "Details": "Sri Satya Sai Group"}],
    "PoliticalAffiliation": "None direct / Educational group.",
    "FundingSource": "University tuition fees, hospital earnings.",
    "SummaryReport": "Established at Pachama, Sehore under Sri Satya Sai University ecosystem. Self-financed."
  },
  {
    "SlNo": "302",
    "CollegeName": "Ram Krishna College Hospital & Research Centre Bhopal",
    "State": "Madhya Pradesh",
    "District": "Bhopal",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Trust",
    "ParentOrganization": "Ram Krishna Group / RKDF Educational Society",
    "KeyPeople": [{"Name": "Dr. Sunil Kapoor", "Role": "Chairman", "Details": "RKDF Group"}],
    "PoliticalAffiliation": "None direct / Educational conglomerate.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in Bhopal under Ram Krishna trust ecosystem. Self-financed."
  },
  {
    "SlNo": "304",
    "CollegeName": "L.N. Medical College and Research Centre Bhopal",
    "State": "Madhya Pradesh",
    "District": "Bhopal",
    "University": "LNCT University Bhopal",
    "Management": "Trust",
    "ParentOrganization": "LNCT Group / Luqui Narayan Charitable Trust",
    "KeyPeople": [
      {"Name": "Jai Narain Chouksey", "Role": "Founder Chairman", "Details": "Chancellor of LNCT University and prominent educationist"},
      {"Name": "Anupam Chouksey", "Role": "Pro-Chancellor", "Details": "LNCT Group"}
    ],
    "PoliticalAffiliation": "Prominent business & political ties across MP.",
    "FundingSource": "LNCT University tuition fees, JK Hospital clinical revenues.",
    "SummaryReport": "Established in 2009 in Bhopal. Flagship constituent of LNCT University. Self-financed."
  },
  {
    "SlNo": "307",
    "CollegeName": "Index Medical College Hospital & Research Centre Indore",
    "State": "Madhya Pradesh",
    "District": "Indore",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Trust",
    "ParentOrganization": "Mayank Welfare Society",
    "KeyPeople": [{"Name": "Suresh Singh Bhadoria", "Role": "Founder Chairman", "Details": "Index Group of Institutions"}],
    "PoliticalAffiliation": "Strong political connections in Malwa/Indore region.",
    "FundingSource": "Group reserves, tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2007 in Indore by Suresh Singh Bhadoria under Mayank Welfare Society. Self-financed."
  },
  {
    "SlNo": "309",
    "CollegeName": "Sri Aurobindo Medical College and Post Graduate Institute Indore",
    "State": "Madhya Pradesh",
    "District": "Indore",
    "University": "Sri Aurobindo University",
    "Management": "Trust",
    "ParentOrganization": "Sri Aurobindo Institute of Medical Sciences (SAIMS Trust)",
    "KeyPeople": [
      {"Name": "Dr. Vinod Bhandari", "Role": "Founder Chairman", "Details": "Prominent surgeon and educationist"},
      {"Name": "Dr. Manjushree Bhandari", "Role": "Chancellor", "Details": "Sri Aurobindo University"}
    ],
    "PoliticalAffiliation": "None direct / Leading healthcare and medical education trust in MP.",
    "FundingSource": "SAIMS University fees, 1400-bed super-specialty hospital clinical earnings.",
    "SummaryReport": "Established in 2003 in Indore by Dr. Vinod Bhandari. Flagship medical university campus in Central India. Self-financed."
  },
  {
    "SlNo": "313",
    "CollegeName": "Ruxmaniben Deepchand Gardi Medical College Ujjain",
    "State": "Madhya Pradesh",
    "District": "Ujjain",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Trust",
    "ParentOrganization": "Ujjain Charitable Trust Hospital & Research Centre",
    "KeyPeople": [{"Name": "Dr. V. K. Saini", "Role": "Trustee & Director", "Details": "Ujjain Charitable Trust"}],
    "PoliticalAffiliation": "None direct / Philanthropic charitable trust.",
    "FundingSource": "Trust endowments, student tuition fees, CR Gardi Hospital earnings.",
    "SummaryReport": "Established in 2001 at Surasa, Ujjain as MP's first private medical college under Ujjain Charitable Trust. Self-funded."
  },
  {
    "SlNo": "314",
    "CollegeName": "LNCT Medical College & Sewakunj Hospital Indore",
    "State": "Madhya Pradesh",
    "District": "Indore",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Society",
    "ParentOrganization": "LNCT Educational Society",
    "KeyPeople": [{"Name": "Jai Narain Chouksey", "Role": "Chairman", "Details": "LNCT Group"}],
    "PoliticalAffiliation": "LNCT Group.",
    "FundingSource": "LNCT Group reserves, tuition fees, Sewakunj Hospital earnings.",
    "SummaryReport": "Established in 2021 in Indore by LNCT Educational Society. Self-financed."
  },
  {
    "SlNo": "315",
    "CollegeName": "Sukh Sagar Medical College & Hospital Jabalpur",
    "State": "Madhya Pradesh",
    "District": "Jabalpur",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Trust",
    "ParentOrganization": "Sukh Sagar Educational Trust",
    "KeyPeople": [{"Name": "Trustees", "Role": "Governing Body", "Details": "Sukh Sagar Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in Jabalpur by Sukh Sagar Educational Trust. Self-financed."
  },
  {
    "SlNo": "316",
    "CollegeName": "Mahaveer Institute of Medical Sciences & Research Bhopal",
    "State": "Madhya Pradesh",
    "District": "Bhopal",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Society",
    "ParentOrganization": "Jain Minority Educational Society",
    "KeyPeople": [{"Name": "Trustees", "Role": "Management", "Details": "Mahaveer Educational Society"}],
    "PoliticalAffiliation": "Jain Minority Institution.",
    "FundingSource": "Minority trust funds, tuition fees, hospital income.",
    "SummaryReport": "Established in 2020 in IT Park, Bhopal as a Jain minority medical college. Self-financed."
  },
  {
    "SlNo": "324",
    "CollegeName": "Amaltas Institute of Medical Sciences Dewas",
    "State": "Madhya Pradesh",
    "District": "Dewas",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Society",
    "ParentOrganization": "Amaltas Educational Welfare Society",
    "KeyPeople": [{"Name": "Suresh Singh Bhadoria", "Role": "Chairman", "Details": "Index & Amaltas Group"}],
    "PoliticalAffiliation": "Strong local political ties.",
    "FundingSource": "Group capital, student tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2016 at Bangar, Dewas by Suresh Singh Bhadoria. Self-financed."
  },
  {
    "SlNo": "325",
    "CollegeName": "RKDF Medical College Hospital & Research Centre Jatkhedi Bhopal",
    "State": "Madhya Pradesh",
    "District": "Bhopal",
    "University": "Sarvepalli Radhakrishnan University Bhopal",
    "Management": "Society",
    "ParentOrganization": "RKDF Educational Society / SRK University",
    "KeyPeople": [{"Name": "Dr. Sunil Kapoor", "Role": "Chairman", "Details": "RKDF Group"}],
    "PoliticalAffiliation": "Prominent educational group in MP.",
    "FundingSource": "SRK University tuition fees, hospital clinical income.",
    "SummaryReport": "Established in 2014 at Jatkhedi, Bhopal as constituent college of SRK University under RKDF Society. Self-financed."
  },
  {
    "SlNo": "326",
    "CollegeName": "Chirayu Medical College and Hospital Bairagarh Bhopal",
    "State": "Madhya Pradesh",
    "District": "Bhopal",
    "University": "Madhya Pradesh Medical Science University Jabalpur",
    "Management": "Trust",
    "ParentOrganization": "Chirayu Charitable Trust",
    "KeyPeople": [{"Name": "Dr. Ajay Goenka", "Role": "Founder Chairman & MD", "Details": "Renowned physician and healthcare entrepreneur"}],
    "PoliticalAffiliation": "Significant political standing during COVID-19 pandemic response in MP.",
    "FundingSource": "Chirayu Group reserves, tuition fees, super-specialty hospital operational income.",
    "SummaryReport": "Established in 2011 at Bairagarh, Bhopal by Dr. Ajay Goenka under Chirayu Charitable Trust. Self-financed."
  },
  {
    "SlNo": "328",
    "CollegeName": "Peoples College of Medical Sciences & Research Centre Bhanpur Bhopal",
    "State": "Madhya Pradesh",
    "District": "Bhopal",
    "University": "Peoples University Bhopal",
    "Management": "Trust",
    "ParentOrganization": "People's Group / People's University Trust",
    "KeyPeople": [
      {"Name": "Suresh N. Vijaywargiya", "Role": "Founder Chairman", "Details": "Industrialist and founder of People's Group"},
      {"Name": "Megha Vijaywargiya", "Role": "Trustee", "Details": "People's University"}
    ],
    "PoliticalAffiliation": "None direct / Educational conglomerate.",
    "FundingSource": "People's University tuition fees, 1000-bed hospital clinical income.",
    "SummaryReport": "Established in 2005 at Bhanpur, Bhopal as constituent college of People's Private University. Self-financed."
  },

  # --- RAJASTHAN ---
  {
    "SlNo": "459",
    "CollegeName": "Sudha Medical College Kota",
    "State": "Rajasthan",
    "District": "Kota",
    "University": "Rajasthan University of Health Sciences",
    "Management": "Society",
    "ParentOrganization": "Sudha Society / Sudha Hospital Group",
    "KeyPeople": [{"Name": "Dr. R. K. Agrawal", "Role": "Chairman", "Details": "Sudha Hospital Kota"}],
    "PoliticalAffiliation": "None direct / Healthcare group in Hadoti region.",
    "FundingSource": "Hospital corporate earnings, tuition fees.",
    "SummaryReport": "Medical college in Kota operated under Sudha Hospital trust ecosystem. Self-financed."
  },
  {
    "SlNo": "460",
    "CollegeName": "Vyas Medical College & Hospital Jodhpur",
    "State": "Rajasthan",
    "District": "Jodhpur",
    "University": "Rajasthan University of Health Sciences Jaipur",
    "Management": "Private",
    "ParentOrganization": "Vyas Group of Institutions / Rajasthan Patrika Trust",
    "KeyPeople": [{"Name": "Manish Vyas", "Role": "Chairman", "Details": "Vyas Group Jodhpur"}],
    "PoliticalAffiliation": "None direct / Educational group.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Medical college at Kudi Haud, Jodhpur operated by Vyas Group. Self-financed."
  },
  {
    "SlNo": "464",
    "CollegeName": "JIET Medical College and Hospital Jodhpur",
    "State": "Rajasthan",
    "District": "Jodhpur",
    "University": "Rajasthan University of Health Sciences Jaipur",
    "Management": "Trust",
    "ParentOrganization": "Jodhpur Institute of Engineering & Technology Trust",
    "KeyPeople": [{"Name": "Er. Navneet Agarwal", "Role": "Chairman", "Details": "JIET Group"}],
    "PoliticalAffiliation": "None direct / Educational trust.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in Mogra, Jodhpur by JIET Trust. Self-financed."
  },
  {
    "SlNo": "473",
    "CollegeName": "Mahatma Gandhi Medical College and Hospital Sitapur Jaipur",
    "State": "Rajasthan",
    "District": "Jaipur",
    "University": "Mahatma Gandhi University of Medical Science & Technology Jaipur",
    "Management": "Trust",
    "ParentOrganization": "India Education Trust",
    "KeyPeople": [
      {"Name": "Dr. M. L. Swarankar", "Role": "Founder Chairman & Emeritus Chancellor", "Details": "Gynecologist, IVF pioneer, and educationist"},
      {"Name": "Dr. Vikas Swarankar", "Role": "Chancellor", "Details": "MGUMST Jaipur"}
    ],
    "PoliticalAffiliation": "None direct / Apex medical university in Rajasthan.",
    "FundingSource": "MGUMST Deemed University fees, 1400-bed super-specialty hospital clinical income.",
    "SummaryReport": "Established in 2000 in Sitapura, Jaipur by Dr. M. L. Swarankar under India Education Trust. Premier self-financed medical university."
  },
  {
    "SlNo": "474",
    "CollegeName": "National Institute of Medical Science & Research Jaipur",
    "State": "Rajasthan",
    "District": "Jaipur",
    "University": "NIMS University Deemed Jaipur",
    "Management": "Trust",
    "ParentOrganization": "NIMS University Trust",
    "KeyPeople": [{"Name": "Prof. Dr. Balvir S. Tomar", "Role": "Founder & Chancellor", "Details": "Pediatric gastroenterologist and founder of NIMS University"}],
    "PoliticalAffiliation": "Significant political standing across Rajasthan & national networks.",
    "FundingSource": "NIMS University tuition fees, super-specialty hospital clinical income.",
    "SummaryReport": "Established in 2004 at Shobha Nagar, Jaipur as constituent medical college of NIMS University. Self-financed."
  },
  {
    "SlNo": "479",
    "CollegeName": "Dr S S Tantia Medical College Hospital & Research Centre Sri Ganganagar",
    "State": "Rajasthan",
    "District": "Sri Ganganagar",
    "University": "Tantia University",
    "Management": "Private",
    "ParentOrganization": "Tantia General Hospital Trust / Tantia University",
    "KeyPeople": [
      {"Name": "Late Dr. S. S. Tantia", "Role": "Founder", "Details": "Physician and educationist"},
      {"Name": "Dr. Mohit Tantia", "Role": "Executive Director", "Details": "Tantia University"}
    ],
    "PoliticalAffiliation": "None direct / Private university group.",
    "FundingSource": "Tantia University tuition fees, hospital operational income.",
    "SummaryReport": "Established in 2021 in Sri Ganganagar as constituent medical college of Tantia University. Self-financed."
  },
  {
    "SlNo": "488",
    "CollegeName": "Ananta Institute of Medical Sciences & Research Centre Rajsamand",
    "State": "Rajasthan",
    "District": "Rajsamand",
    "University": "Rajasthan University of Health Sciences",
    "Management": "Society",
    "ParentOrganization": "Ananta Charitable Educational Society",
    "KeyPeople": [{"Name": "Nitin Sharma", "Role": "Chairman", "Details": "Ananta Group"}],
    "PoliticalAffiliation": "None direct / Educational society.",
    "FundingSource": "Tuition fees, hospital earnings.",
    "SummaryReport": "Established in 2015 at Kaliwas, Rajsamand by Ananta Charitable Educational Society. Self-financed."
  },
  {
    "SlNo": "489",
    "CollegeName": "Jaipur National University Institute of Medical Sciences and Research Centre Jagatpura Jaipur",
    "State": "Rajasthan",
    "District": "Jaipur",
    "University": "Jaipur National University Private",
    "Management": "Private",
    "ParentOrganization": "Mahima Shiksha Samiti / Jaipur National University",
    "KeyPeople": [{"Name": "Prof. Dr. Sandeep Bakshi", "Role": "Founder & Chancellor", "Details": "JNU Jaipur"}],
    "PoliticalAffiliation": "None direct / Leading private university in Rajasthan.",
    "FundingSource": "JNU University tuition fees, 800-bed hospital clinical income.",
    "SummaryReport": "Established in 2015 at Jagatpura, Jaipur as constituent college of Jaipur National Private University. Self-financed."
  },
  {
    "SlNo": "490",
    "CollegeName": "Pacific Institute of Medical Sciences Umarda Udaipur",
    "State": "Rajasthan",
    "District": "Udaipur",
    "University": "Sai Tirupati University Udaipur",
    "Management": "Society",
    "ParentOrganization": "Sai Tirupati University / Ashish Society",
    "KeyPeople": [{"Name": "Ashish Agarwal", "Role": "Chairperson", "Details": "Sai Tirupati University"}],
    "PoliticalAffiliation": "None direct / Educational group.",
    "FundingSource": "University fees, hospital clinical income.",
    "SummaryReport": "Established in 2014 at Umarda, Udaipur as constituent college of Sai Tirupati University. Self-financed."
  },
  {
    "SlNo": "491",
    "CollegeName": "Geetanjali Institute of Medical Sciences Udaipur",
    "State": "Rajasthan",
    "District": "Udaipur",
    "University": "Rajasthan University of Health Sciences",
    "Management": "Trust",
    "ParentOrganization": "Geetanjali University Trust / PAHER Society",
    "KeyPeople": [{"Name": "J. P. Agarwal", "Role": "Founder & Chairman", "Details": "Industrialist and Chancellor of Geetanjali University"}],
    "PoliticalAffiliation": "Prominent business & regional political connections in Mewar region.",
    "FundingSource": "Geetanjali University fees, 1200-bed super-specialty hospital clinical revenues.",
    "SummaryReport": "Established in 2008 in Udaipur by J. P. Agarwal. Flagship constituent of Geetanjali Medical University. Self-financed."
  },
  {
    "SlNo": "492",
    "CollegeName": "American International Institute of Medical Sciences Bedwas",
    "State": "Rajasthan",
    "District": "Udaipur",
    "University": "Rajasthan University of Health Sciences",
    "Management": "Private",
    "ParentOrganization": "Devraj Education Trust / GBH American Hospital",
    "KeyPeople": [{"Name": "Dr. Devansh Yadav", "Role": "Director", "Details": "GBH American Hospital"}],
    "PoliticalAffiliation": "None direct / Corporate hospital group.",
    "FundingSource": "GBH American Hospital corporate earnings, tuition fees.",
    "SummaryReport": "Established in 2016 at Bedwas, Udaipur by Devraj Education Trust in partnership with GBH American Hospital. Self-financed."
  },
  {
    "SlNo": "498",
    "CollegeName": "Pacific Medical College & Hospital Bhilo Ka Bedla Udaipur",
    "State": "Rajasthan",
    "District": "Udaipur",
    "University": "Pacific Medical University Udaipur",
    "Management": "Trust",
    "ParentOrganization": "Tirupati Balaji Educational Trust / Pacific Medical University",
    "KeyPeople": [{"Name": "Rahul Agarwal", "Role": "Chairman", "Details": "Pacific Medical University"}],
    "PoliticalAffiliation": "None direct / Educational conglomerate in Udaipur.",
    "FundingSource": "University fees, 900-bed hospital clinical income.",
    "SummaryReport": "Established in 2014 at Bhilo Ka Bedla, Udaipur as constituent college of Pacific Medical University. Self-financed."
  }
]

north_west_sources = [
  {"SlNo": "659", "CollegeName": "Autonomous State Medical College and Hospital Gonda", "Sources": ["https://asmcgonda.edu.in/"]},
  {"SlNo": "660", "CollegeName": "Autonomous State Medical College and Hospital Lakhimpur Kheri", "Sources": ["https://asmckheri.edu.in/"]},
  {"SlNo": "664", "CollegeName": "Dr. B.S. Kushwah Medical College Kanpur", "Sources": ["https://ramamedicalcolleges.com/"]},
  {"SlNo": "665", "CollegeName": "SKS Hospital Medical College & Research Centre Mathura", "Sources": ["https://sksmedicalcollege.com/"]},
  {"SlNo": "667", "CollegeName": "Major S D Singh Medical College and Hospital Fathehgarh Farrukhabad", "Sources": ["https://majorsdsinghmedicalcollege.com/"]},
  {"SlNo": "671", "CollegeName": "Teerthanker Mahaveer Medical College Moradabad", "Sources": ["https://tmu.ac.in/medical-college-and-research-centre/"]},
  {"SlNo": "673", "CollegeName": "Muzaffarnagar Medical College Muzaffarnagar", "Sources": ["https://mmc.ac.in/"]},
  {"SlNo": "674", "CollegeName": "Santosh Medical College Ghaziabad", "Sources": ["https://santosh.ac.in/"]},
  {"SlNo": "679", "CollegeName": "Era Lucknow Medical College Lucknow", "Sources": ["https://erauniversity.in/"]},
  {"SlNo": "682", "CollegeName": "Rohilkhand Medical College & Hospital Bareilly", "Sources": ["https://rmchbareilly.edu.in/"]},
  {"SlNo": "683", "CollegeName": "Subharti Medical College Meerut", "Sources": ["https://subharti.org/medical/"]},
  {"SlNo": "685", "CollegeName": "Hind Institute of Medical Sciences Barabanki", "Sources": ["https://himsup.com/"]},
  {"SlNo": "696", "CollegeName": "Naraina Medical College & Research Centre Kanpur", "Sources": ["https://narainamedical.com/"]},
  {"SlNo": "697", "CollegeName": "Noida International Institute Of Medical Sciences Noida", "Sources": ["https://niims.edu.in/"]},
  {"SlNo": "698", "CollegeName": "United Institute of Medical Sciences Allahabad", "Sources": ["https://uims.unitedmedcity.com/"]},
  {"SlNo": "706", "CollegeName": "National Capital Region Institute of Medical Sciences Meerut", "Sources": ["https://ncrims.org/"]},
  {"SlNo": "707", "CollegeName": "G.S. Medical College & Hospital Hapur", "Sources": ["https://gsmc.edu.in/"]},
  {"SlNo": "709", "CollegeName": "Varun Arjun Medical College Banthra Shahjahanpur", "Sources": ["https://vamc.in/"]},
  {"SlNo": "710", "CollegeName": "Saraswati Medical College Unnao", "Sources": ["https://saraswatimedical.ac.in/"]},
  {"SlNo": "711", "CollegeName": "Krishna Mohan Medical College & Hospital Mathura", "Sources": ["https://kmmch.in/"]},
  {"SlNo": "712", "CollegeName": "Venkateshwara Institute of Medical Sciences Gajraula", "Sources": ["https://vims.ac.in/"]},
  {"SlNo": "713", "CollegeName": "Prasad Institute of Medical Sciences Lucknow", "Sources": ["https://pimslko.edu.in/"]},
  {"SlNo": "714", "CollegeName": "T S Misra Medical College & Hospital Amusi Lucknow", "Sources": ["https://tsmisra.in/"]},
  {"SlNo": "716", "CollegeName": "K.D. Medical College Hospital & Research Centre Mathura", "Sources": ["https://kdmch.in/"]},
  {"SlNo": "718", "CollegeName": "Heritage Institute of Medical Sciences Varanasi", "Sources": ["https://heritageims.com/"]},
  {"SlNo": "719", "CollegeName": "Hind Institute of Medical Sciences Sitapur", "Sources": ["https://himssitapur.org/"]},
  {"SlNo": "720", "CollegeName": "F.H. Medical College & Hospital Etamdapur Agra", "Sources": ["https://fhmc.org.in/"]},
  {"SlNo": "721", "CollegeName": "Rajshree Medical Research Institute Bareilly", "Sources": ["https://rmri.ac.in/"]},
  {"SlNo": "723", "CollegeName": "Integral Institute of Medical Sciences & Research Lucknow", "Sources": ["https://iul.ac.in/iimsr/"]},
  {"SlNo": "725", "CollegeName": "Mayo Institute of Medical Sciences Barabanki", "Sources": ["https://mimsup.in/"]},
  {"SlNo": "727", "CollegeName": "Rama Medical College Hospital and Research Centre Hapur", "Sources": ["https://ramamedicalcolleges.com/hapur/"]},
  {"SlNo": "728", "CollegeName": "Career Instt. Of Medical Sciences & Hospital Lucknow", "Sources": ["https://careermedical.in/"]},
  {"SlNo": "729", "CollegeName": "School of Medical Sciences & Research Greater Noida", "Sources": ["https://sharda.ac.in/"]},
  {"SlNo": "730", "CollegeName": "Rama Medical College and Hospital Kanpur", "Sources": ["https://ramamedicalcolleges.com/kanpur/"]},
  {"SlNo": "731", "CollegeName": "Saraswati Institute of Medical Sciences Hapur", "Sources": ["https://sims.edu.in/"]},
  {"SlNo": "732", "CollegeName": "Shri Ram Murti Smarak Institute of Medical Sciences Bareilly", "Sources": ["https://srms.ac.in/ims/"]},

  {"SlNo": "106", "CollegeName": "Bhagyoday Medical College", "Sources": ["https://bhagyoday.org/"]},
  {"SlNo": "107", "CollegeName": "SAL Institute of Medical Sciences Ahmedabad", "Sources": ["https://salhospital.com/"]},
  {"SlNo": "108", "CollegeName": "Swaminarayan Institute of Medical Sciences & Research", "Sources": ["https://swaminarayanuniversity.ac.in/"]},
  {"SlNo": "114", "CollegeName": "SBKS Medical Instt. & Research Centre Vadodra", "Sources": ["https://sumandeepvidyapeethdu.edu.in/"]},
  {"SlNo": "115", "CollegeName": "CU Shah Medical College Surendra Nagar", "Sources": ["https://cumctrust.org/"]},
  {"SlNo": "120", "CollegeName": "Dr. Kiran C. Patel Medical College and Research Institute Bharuch", "Sources": ["https://kiranpatelmedcollege.com/"]},
  {"SlNo": "121", "CollegeName": "Shantabaa Medical College Amreli", "Sources": ["https://smc.gajeratrust.org/"]},
  {"SlNo": "122", "CollegeName": "Nootan Medical College and Research Centre Mehsana", "Sources": ["https://nootanmedical.org/"]},
  {"SlNo": "123", "CollegeName": "Dr. N.D. Desai Faculty of Medical Science and Research Nadiad", "Sources": ["https://ddu.ac.in/"]},
  {"SlNo": "124", "CollegeName": "Kiran Medical College Surat", "Sources": ["https://kiran.hospital/"]},
  {"SlNo": "125", "CollegeName": "Zydus Medical College & Hospital Dahod", "Sources": ["https://zydusmedicalcollege.org/"]},
  {"SlNo": "126", "CollegeName": "Banas Medical College and Research Institute Palanpur", "Sources": ["https://bmcri.co.in/"]},
  {"SlNo": "128", "CollegeName": "Dr. M.K. Shah Medical College & Research Centre Ahmedabad", "Sources": ["https://mkshahmedical.org/"]},
  {"SlNo": "129", "CollegeName": "Parul Institute of Medical Sciences & Research Vadodara", "Sources": ["https://paruluniversity.ac.in/pimsr/"]},
  {"SlNo": "135", "CollegeName": "GCS Medical College Ahmedabad", "Sources": ["https://gcsmc.org/"]},
  {"SlNo": "138", "CollegeName": "Gujarat Adani Institute of Medical Sciences Bhuj", "Sources": ["https://gaims.ac.in/"]},
  {"SlNo": "142", "CollegeName": "Ananya College of Medicine & Research Kalol", "Sources": ["https://ananyamedical.org/"]},
  {"SlNo": "146", "CollegeName": "Pramukhswami Medical College Karmsad", "Sources": ["https://charutarhealth.org/"]},

  {"SlNo": "299", "CollegeName": "School of Medical Sciences Sri Satya Sai University of Technology and Medical Sciences Sehore", "Sources": ["https://sssutms.co.in/"]},
  {"SlNo": "302", "CollegeName": "Ram Krishna College Hospital & Research Centre Bhopal", "Sources": ["https://rkdf.ac.in/"]},
  {"SlNo": "304", "CollegeName": "L.N. Medical College and Research Centre Bhopal", "Sources": ["https://lnctuniversity.ac.in/lnmc/"]},
  {"SlNo": "307", "CollegeName": "Index Medical College Hospital & Research Centre Indore", "Sources": ["https://indexgroup.co.in/"]},
  {"SlNo": "309", "CollegeName": "Sri Aurobindo Medical College and Post Graduate Institute Indore", "Sources": ["https://saimsonline.com/"]},
  {"SlNo": "313", "CollegeName": "Ruxmaniben Deepchand Gardi Medical College Ujjain", "Sources": ["https://rdgmc.edu.in/"]},
  {"SlNo": "314", "CollegeName": "LNCT Medical College & Sewakunj Hospital Indore", "Sources": ["https://lnctmedicalcollege.in/"]},
  {"SlNo": "315", "CollegeName": "Sukh Sagar Medical College & Hospital Jabalpur", "Sources": ["https://sukhsagar.edu.in/"]},
  {"SlNo": "316", "CollegeName": "Mahaveer Institute of Medical Sciences & Research Bhopal", "Sources": ["https://mimsbhopal.com/"]},
  {"SlNo": "324", "CollegeName": "Amaltas Institute of Medical Sciences Dewas", "Sources": ["https://amaltas.edu.in/"]},
  {"SlNo": "325", "CollegeName": "RKDF Medical College Hospital & Research Centre Jatkhedi Bhopal", "Sources": ["https://srku.edu.in/rkdfmc/"]},
  {"SlNo": "326", "CollegeName": "Chirayu Medical College and Hospital Bairagarh Bhopal", "Sources": ["https://chirayukankali.org/"]},
  {"SlNo": "328", "CollegeName": "Peoples College of Medical Sciences & Research Centre Bhanpur Bhopal", "Sources": ["https://peoplesuniversity.edu.in/medical/"]},

  {"SlNo": "459", "CollegeName": "Sudha Medical College Kota", "Sources": ["https://sudhahospital.com/"]},
  {"SlNo": "460", "CollegeName": "Vyas Medical College & Hospital Jodhpur", "Sources": ["https://vyasmedicalcollege.com/"]},
  {"SlNo": "464", "CollegeName": "JIET Medical College and Hospital Jodhpur", "Sources": ["https://jietjodhpur.ac.in/"]},
  {"SlNo": "473", "CollegeName": "Mahatma Gandhi Medical College and Hospital Sitapur Jaipur", "Sources": ["https://mgmch.org/"]},
  {"SlNo": "474", "CollegeName": "National Institute of Medical Science & Research Jaipur", "Sources": ["https://nimsuniversity.org/"]},
  {"SlNo": "479", "CollegeName": "Dr S S Tantia Medical College Hospital & Research Centre Sri Ganganagar", "Sources": ["https://tantiagroup.com/"]},
  {"SlNo": "488", "CollegeName": "Ananta Institute of Medical Sciences & Research Centre Rajsamand", "Sources": ["https://anantamedcity.com/"]},
  {"SlNo": "489", "CollegeName": "Jaipur National University Institute of Medical Sciences and Research Centre Jagatpura Jaipur", "Sources": ["https://jnujaipur.ac.in/medical-college/"]},
  {"SlNo": "490", "CollegeName": "Pacific Institute of Medical Sciences Umarda Udaipur", "Sources": ["https://pimsudaipur.edu.in/"]},
  {"SlNo": "491", "CollegeName": "Geetanjali Institute of Medical Sciences Udaipur", "Sources": ["https://geetanjaliuniversity.com/"]},
  {"SlNo": "492", "CollegeName": "American International Institute of Medical Sciences Bedwas", "Sources": ["https://aiimsudaipur.org/"]},
  {"SlNo": "498", "CollegeName": "Pacific Medical College & Hospital Bhilo Ka Bedla Udaipur", "Sources": ["https://pacificmedicalcollege.ac.in/"]}
]

own.extend(north_west_records)
src.extend(north_west_sources)

save_db(own, src)
